# Installation de pandas

In [ ]:
!pip install pandas

# Importation de libraries

In [1]:
import pandas as pd

# Nettoyage de données

In [10]:
raw_data = pd.read_csv("../data/raw/flight_data_2024_sample.csv")

### Aperçu rapide

In [4]:
raw_data.head()

,year,month,day_of_month,day_of_week,fl_date,op_unique_carrier,op_carrier_fl_num,origin,origin_city_name,origin_state_nm,...,diverted,crs_elapsed_time,actual_elapsed_time,air_time,distance,carrier_delay,weather_delay,nas_delay,security_delay,late_aircraft_delay
0,2024,4,18,4,2024-04-18,MQ,3535.0,DFW,"Dallas/Fort Worth, TX",Texas,...,0,151.0,144.0,119.0,835.0,0,0,0,0,0
1,2024,1,1,1,2024-01-01,AA,148.0,CLT,"Charlotte, NC",North Carolina,...,0,286.0,273.0,253.0,1773.0,0,0,0,0,0
2,2024,12,12,4,2024-12-12,9E,5440.0,CHA,"Chattanooga, TN",Tennessee,...,0,59.0,50.0,29.0,106.0,0,0,0,0,0
3,2024,4,8,1,2024-04-08,WN,1971.0,OMA,"Omaha, NE",Nebraska,...,0,180.0,177.0,163.0,1099.0,0,0,0,0,0
4,2024,2,16,5,2024-02-16,WN,862.0,BWI,"Baltimore, MD",Maryland,...,0,90.0,96.0,76.0,399.0,0,0,0,0,0

# 1. Compréhension et exploration du dataset
## Avant de commencer le nettoyage des données, nous allons commencer par mieux comprendre les informations qu'il contient.

In [5]:
raw_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 35 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   year                 10000 non-null  int64
 1   month                10000 non-null  int64
 2   day_of_month         10000 non-null  int64
 3   day_of_week          10000 non-null  int64
 4   fl_date              10000 non-null  object
 5   op_unique_carrier    10000 non-null  object
 6   op_carrier_fl_num    10000 non-null  float64
 7   origin               10000 non-null  object
 8   origin_city_name     10000 non-null  object
 9   origin_state_nm      10000 non-null  object
 10  dest                 10000 non-null  object
 11  dest_city_name       10000 non-null  object
 12  dest_state_nm        10000 non-null  object
 13  crs_dep_time         10000 non-null  int64
 14  dep_time             9884 non-null   float64
 15  dep_delay            9884 non-null   float64
 16  taxi_out             9880 non-null   float64
 17  wheels_off           9880 non-null   float64
 18  wheels_on            9873 non-null   float64
 19  taxi_in              9873 non-null   float64
 20  crs_arr_time         10000 non-null  int64
 21  arr_time             9873 non-null   float64
 22  arr_delay            9836 non-null   float64
 23  cancelled            10000 non-null  int64
 24  cancellation_code    122 non-null    object
 25  diverted             10000 non-null  int64
 26  crs_elapsed_time     10000 non-null  float64
 27  actual_elapsed_time  9836 non-null   float64
 28  air_time             9836 non-null   float64
 29  distance             10000 non-null  float64
 30  carrier_delay        10000 non-null  int64
 31  weather_delay        10000 non-null  int64
 32  nas_delay            10000 non-null  int64
 33  security_delay       10000 non-null  int64
 34  late_aircraft_delay  10000 non-null  int64
dtypes: float64(13), int64(13), object(9)
memory usage: 2.7+ MB

In [6]:
raw_data.describe()

,year,month,day_of_month,day_of_week,op_carrier_fl_num,crs_dep_time,dep_time,dep_delay,taxi_out,wheels_off,...,diverted,crs_elapsed_time,actual_elapsed_time,air_time,distance,carrier_delay,weather_delay,nas_delay,security_delay,late_aircraft_delay
count,10000.0,10000.000000,10000.000000,10000.00000,10000.000000,10000.000000,9884.000000,9884.000000,9880.000000,9880.000000,...,10000.000000,10000.000000,9836.000000,9836.000000,10000.000000,10000.000000,10000.000000,10000.000000,10000.000000,10000.000000
mean,2024.0,6.613200,15.843000,3.95020,2529.762600,1324.447700,1330.160664,13.002428,17.878644,1353.564879,...,0.004200,147.372500,141.727837,115.445506,838.346600,4.870900,1.083100,3.027100,0.008800,6.142200
std,0.0,3.377858,8.792774,2.00637,1655.998442,488.544631,504.953299,53.614819,9.773379,507.452551,...,0.064674,72.931101,72.786088,70.736184,598.526507,33.502392,15.821031,15.755545,0.381231,29.632624
min,2024.0,1.000000,1.000000,1.00000,1.000000,22.000000,1.000000,-22.000000,4.000000,1.000000,...,0.000000,23.000000,17.000000,8.000000,31.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,2024.0,4.000000,8.000000,2.00000,1172.000000,905.000000,910.000000,-6.000000,12.000000,928.750000,...,0.000000,93.000000,89.000000,64.000000,404.000000,0.000000,0.000000,0.000000,0.000000,0.000000
50%,2024.0,7.000000,16.000000,4.00000,2254.000000,1320.000000,1324.000000,-2.000000,15.000000,1337.000000,...,0.000000,130.000000,125.000000,98.000000,680.000000,0.000000,0.000000,0.000000,0.000000,0.000000
75%,2024.0,10.000000,23.000000,6.00000,3742.000000,1734.250000,1745.000000,9.250000,21.000000,1759.000000,...,0.000000,179.000000,174.000000,145.000000,1072.000000,0.000000,0.000000,0.000000,0.000000,0.000000
max,2024.0,12.000000,31.000000,7.00000,8771.000000,2359.000000,2400.000000,2011.000000,154.000000,2400.000000,...,1.000000,685.000000,691.000000,635.000000,5095.000000,2011.000000,664.000000,454.000000,22.000000,995.000000

In [7]:
raw_data.shape

(10000, 35)

In [8]:
raw_data.columns

Index(['year', 'month', 'day_of_month', 'day_of_week', 'fl_date',
       'op_unique_carrier', 'op_carrier_fl_num', 'origin', 'origin_city_name',
       'origin_state_nm', 'dest', 'dest_city_name', 'dest_state_nm',
       'crs_dep_time', 'dep_time', 'dep_delay', 'taxi_out', 'wheels_off',
       'wheels_on', 'taxi_in', 'crs_arr_time', 'arr_time', 'arr_delay',
       'cancelled', 'cancellation_code', 'diverted', 'crs_elapsed_time',
       'actual_elapsed_time', 'air_time', 'distance', 'carrier_delay',
       'weather_delay', 'nas_delay', 'security_delay', 'late_aircraft_delay'],
      dtype='object')

## 2. Traitement des valeurs manquantes
### A partir de là, nous allons commencer le nettoyage de ces données, en commencant par détécter et traiter les valeurs manquantes

In [9]:
raw_data.isnull().sum()

year                      0
month                     0
day_of_month              0
day_of_week               0
fl_date                   0
op_unique_carrier         0
op_carrier_fl_num         0
origin                    0
origin_city_name          0
origin_state_nm           0
dest                      0
dest_city_name            0
dest_state_nm             0
crs_dep_time              0
dep_time                116
dep_delay               116
taxi_out                120
wheels_off              120
wheels_on               127
taxi_in                 127
crs_arr_time              0
arr_time                127
arr_delay               164
cancelled                 0
cancellation_code      9878
diverted                  0
crs_elapsed_time          0
actual_elapsed_time     164
air_time                164
distance                  0
carrier_delay             0
weather_delay             0
nas_delay                 0
security_delay            0
late_aircraft_delay       0
dtype: int64